<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />

<meta name="author" content="Andy Lyons" />

<meta name="date" content="2015-09-10" />

<title>Computing Isopleth Overlap for All Pairs of Hullsets</title>

<script src="isopleth_overlap_auto_files/jquery-1.11.0/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="isopleth_overlap_auto_files/bootstrap-3.3.1/css/bootstrap.min.css" rel="stylesheet" />
<script src="isopleth_overlap_auto_files/bootstrap-3.3.1/js/bootstrap.min.js"></script>
<script src="isopleth_overlap_auto_files/bootstrap-3.3.1/shim/html5shiv.min.js"></script>
<script src="isopleth_overlap_auto_files/bootstrap-3.3.1/shim/respond.min.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<link rel="stylesheet"
      href="isopleth_overlap_auto_files/highlight/default.css"
      type="text/css" />
<script src="isopleth_overlap_auto_files/highlight/highlight.js"></script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img { 
  max-width:100%; 
  height: auto; 
}
</style>
<div class="container-fluid main-container">


<div id="header">
<h1 class="title">Computing Isopleth Overlap for All Pairs of Hullsets</h1>
<h4 class="author"><em>Andy Lyons</em></h4>
<h4 class="date"><em>September 10, 2015</em></h4>
</div>


<style>
strong > em {color:red; font-style:normal;}
</style>
<p>In this tip, we demonstrate how to compute the area of overlap for pairs of hullsets (e.g., indviduals) using the <code>lhs.iso.overlap</code> function from the <tt>tlocoh.dev</tt> package.</p>
<div id="create-some-sample-data" class="section level3">
<h3>Create Some Sample Data</h3>
<p>First let’s create some fake movement data. We’ll create random walks for 10 indviduals, with 100 points each.</p>
<pre class="r"><code>step_size &lt;- 5
xys_all &lt;- NULL
num_id &lt;- 10
num_pts &lt;- 100
for (i in 1:num_id) {
    id &lt;- sprintf(&quot;ID%04d&quot;, i)
    theta &lt;- runif(num_pts, min = 0, max = 2 *pi)
    start_loc &lt;- runif(2, min=500, max=600)
    xys_this &lt;- data.frame(id=id, 
                           x=start_loc[1] + step_size * cumsum(cos(theta)),
                           y=start_loc[2] + step_size * cumsum(sin(theta)))
    xys_all &lt;- rbind(xys_all, xys_this)
}
head(xys_all)</code></pre>
<pre><code>##       id   x   y
## 1 ID0001 507 560
## 2 ID0001 504 556
## 3 ID0001 500 553
## 4 ID0001 496 550
## 5 ID0001 499 546
## 6 ID0001 496 542</code></pre>
<p>For a bit of realism, we’ll offset the locations so they’ll appear in Kansas.</p>
<pre class="r"><code>xys_all &lt;- transform(xys_all, x = x + 71000, y = y + 4257200)</code></pre>
</div>
<div id="convert-to-a-locoh-xy-object" class="section level3">
<h3>Convert to a locoh-xy Object</h3>
<p>Next, we can convert our points to a locoh-xy object. Let’s first load the <tt>tlocoh</tt> package.</p>
<pre class="r"><code>require(tlocoh)</code></pre>
<pre><code>## Loading required package: tlocoh
## Loading required package: sp
## T-LoCoH for R (version 1.36.0)
## URL: http://tlocoh.r-forge.r-project.org/
## Bug reports: tlocoh@gmail.com</code></pre>
<pre class="r"><code>## Make sure you&#39;re using version 1.36.00 or later.
packageVersion(&quot;tlocoh&quot;)</code></pre>
<pre><code>## [1] &#39;1.36.0&#39;</code></pre>
<pre class="r"><code>dummy.lxy &lt;- xyt.lxy(xy=xys_all[ ,2:3],id=xys_all[ ,1], proj4string = CRS(&quot;+proj=utm +zone=14 +ellps=WGS84&quot;))
plot(dummy.lxy, overlay=T, title.show=F)</code></pre>
<p><img src="isopleth_overlap_auto_files/figure-html/unnamed-chunk-3-1.png" title="" alt="" width="672" /></p>
</div>
<div id="create-hulls-and-isopleths" class="section level3">
<h3>Create Hulls and Isopleths</h3>
<p>To create hulls, we first identify nearest neighbors. There’s a process to go through to decide how many neighbors to build hulls with, but we’ll just use k=10 for now.</p>
<pre class="r"><code>dummy.lxy &lt;- lxy.nn.add(dummy.lxy, s=0, k=10, status=FALSE)
summary(dummy.lxy)</code></pre>
<pre><code>## Summary of LoCoH-xy object: dummy.lxy 
## ***Locations
##        id num.pts dups
##    ID0001     100    0
##    ID0002     100    0
##    ID0003     100    0
##    ID0004     100    0
##    ID0005     100    0
##    ID0006     100    0
##    ID0007     100    0
##    ID0008     100    0
##    ID0009     100    0
##    ID0010     100    0
## ***Time span
##    no times recorded 
## ***Spatial extent 
##    ID0001
##      x: 71467.4 - 71507.3 
##      y: 4257736.4 - 4257824.1 
##    ID0002
##      x: 71500.7 - 71578.9 
##      y: 4257776 - 4257817.2 
##    ID0003
##      x: 71528.7 - 71590 
##      y: 4257732.9 - 4257759.8 
##    ID0004
##      x: 71566.6 - 71607.1 
##      y: 4257700.1 - 4257753.3 
##    ID0005
##      x: 71472.7 - 71520.9 
##      y: 4257707.6 - 4257788.5 
##    ID0006
##      x: 71519.5 - 71570.4 
##      y: 4257730.2 - 4257784.2 
##    ID0007
##      x: 71584.6 - 71610.5 
##      y: 4257697 - 4257725.3 
##    ID0008
##      x: 71512.1 - 71569.4 
##      y: 4257721.8 - 4257764 
##    ID0009
##      x: 71511.1 - 71558.2 
##      y: 4257791.1 - 4257832.2 
##    ID0010
##      x: 71529.4 - 71598.3 
##      y: 4257764.1 - 4257804 
##   proj: +proj=utm +zone=14 +ellps=WGS84
## ***Ancilliary Variables: 
##    -none- 
## ***Nearest-neighbor set(s): 
##    1 ID0001|vmax|s0|n100|kmax10|rmax4.5|amax30.7
##    2 ID0002|vmax|s0|n100|kmax10|rmax4.5|amax30
##    3 ID0003|vmax|s0|n100|kmax10|rmax3.6|amax23.3
##    4 ID0004|vmax|s0|n100|kmax10|rmax4.5|amax27.8
##    5 ID0005|vmax|s0|n100|kmax10|rmax4.6|amax31
##    6 ID0006|vmax|s0|n100|kmax10|rmax3.5|amax26
##    7 ID0007|vmax|s0|n100|kmax10|rmax2.9|amax18
##    8 ID0008|vmax|s0|n100|kmax10|rmax4.8|amax34.3
##    9 ID0009|vmax|s0|n100|kmax10|rmax4.3|amax26.3
##    10 ID0010|vmax|s0|n100|kmax10|rmax2.9|amax17.5</code></pre>
<p>Next, we make a hullset object. We’ll add the <code>iso.add=TRUE</code> argument to create default density isopleths at the same time and specify the isopleth levels we want to use with <code>iso.levels</code>.</p>
<pre class="r"><code>dummy.lhs &lt;- lxy.lhs(dummy.lxy, k=10, s=0, iso.add=TRUE, iso.levels = c(0.5, 0.95), status=FALSE)</code></pre>
<p>Let’s inspect isopleths for one of the individuals.</p>
<pre class="r"><code>plot(dummy.lhs, iso=TRUE, id=&quot;ID0005&quot;, allpts=T, col.allpts=&quot;gray30&quot;, cex.allpts=0.4)</code></pre>
<p><img src="isopleth_overlap_auto_files/figure-html/isoplot_one-1.png" title="" alt="" width="672" /></p>
<p>Now we’ll plot an overlay of the isopleths for all of the individuals.</p>
<pre class="r"><code>plot(dummy.lhs, iso=TRUE, overlay=TRUE, col.overlay.byhullset=TRUE, gmap=&quot;hybrid&quot;)</code></pre>
<pre><code>## Downloading common background image...Done</code></pre>
<p><img src="isopleth_overlap_auto_files/figure-html/isoplot_all-1.png" title="" alt="" width="672" /></p>
</div>
<div id="find-isopleth-intersections" class="section level3">
<h3>Find Isopleth Intersections</h3>
<p>Some of these virtual indviduals appear to overlap. Let’s find which ones using the function <code>lhs.iso.overlap</code>. This function will take all pairs of individuals, and find the area of intersection. This function is currently in the <tt>toloch.dev</tt> package, which is the package for ‘experimental’ functions for T‑LoCoH.</p>
<pre class="r"><code>## Make sure you&#39;re using version 1.3.01 or later.
if (!require(tlocoh.dev)) install.packages(&quot;tlocoh.dev&quot;, repos=&quot;http://R-Forge.R-project.org&quot;)</code></pre>
<pre><code>## Loading required package: tlocoh.dev
## Development features for T-LoCoH
## Version 1.3.01
## URL: http://tlocoh.r-forge.r-project.org/
## Please send bug reports and feature requests to tlocoh@gmail.com</code></pre>
<pre class="r"><code>require(tlocoh.dev)</code></pre>
<p>The function we want to use is <code>lhs.iso.overlap</code>. This function will look at all pairs of hullsets in <code>dummy.lhs</code> (which in our case correspond to different individuals), and compute the area of intersection.</p>
<pre class="r"><code>overlap_stats &lt;- lhs.iso.overlap(dummy.lhs, iso.level=0.95, status=FALSE)
names(overlap_stats)</code></pre>
<pre><code>## [1] &quot;spdf&quot;         &quot;overlap_area&quot; &quot;overlap_prop&quot;</code></pre>
<p><code>lhs.iso.overlap</code> returns a named list with three elements. The <strong>spdf</strong> element is a SpatialPolygonsDataFrame contained the polygons of intersection. We can plot it on top of the isopleths:</p>
<pre class="r"><code>plot(dummy.lhs, iso=TRUE, overlay=TRUE, col.overlay.byhullset=TRUE)
plot(overlap_stats$spdf, col=&quot;#32323280&quot;, add=TRUE)</code></pre>
<p><img src="isopleth_overlap_auto_files/figure-html/plot_areaoverlap-1.png" title="" alt="" width="672" /></p>
<p>The data table (or attribute table) for the areas of intersection of two ids contains the area expressed in map units, as well as a proportion of the two hullsets.</p>
<pre class="r"><code>pander( head(overlap_stats$spdf@data) )</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">hs1name</th>
<th align="right">hs2name</th>
<th align="right">iso_level</th>
<th align="right">area</th>
<th align="right">area_prhs1</th>
<th align="right">area_prhs2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">ID0001.pts100.k10.s0.kmin0</td>
<td align="right">ID0002.pts100.k10.s0.kmin0</td>
<td align="right">0.95</td>
<td align="right">20.78</td>
<td align="right">0.01904</td>
<td align="right">0.02144</td>
</tr>
<tr class="even">
<td align="right">ID0001.pts100.k10.s0.kmin0</td>
<td align="right">ID0005.pts100.k10.s0.kmin0</td>
<td align="right">0.95</td>
<td align="right">126.1</td>
<td align="right">0.1155</td>
<td align="right">0.1269</td>
</tr>
<tr class="odd">
<td align="right">ID0002.pts100.k10.s0.kmin0</td>
<td align="right">ID0009.pts100.k10.s0.kmin0</td>
<td align="right">0.95</td>
<td align="right">306.9</td>
<td align="right">0.3166</td>
<td align="right">0.4001</td>
</tr>
<tr class="even">
<td align="right">ID0002.pts100.k10.s0.kmin0</td>
<td align="right">ID0010.pts100.k10.s0.kmin0</td>
<td align="right">0.95</td>
<td align="right">71.34</td>
<td align="right">0.0736</td>
<td align="right">0.09879</td>
</tr>
<tr class="odd">
<td align="right">ID0003.pts100.k10.s0.kmin0</td>
<td align="right">ID0004.pts100.k10.s0.kmin0</td>
<td align="right">0.95</td>
<td align="right">112.7</td>
<td align="right">0.1775</td>
<td align="right">0.09494</td>
</tr>
<tr class="even">
<td align="right">ID0003.pts100.k10.s0.kmin0</td>
<td align="right">ID0006.pts100.k10.s0.kmin0</td>
<td align="right">0.95</td>
<td align="right">229.3</td>
<td align="right">0.3612</td>
<td align="right">0.3959</td>
</tr>
</tbody>
</table>
<p>The SpatialPolygonsDataFrame could also be exported for use in a GIS program using the <tt>rgdal</tt> package.</p>
<p>The <strong>overlap_area</strong> and <strong>overlap_prop</strong> elements contain matrices of the area of intersection expressed as i) map units and ii) proportions of the areas of isopleths. We can inspect the comparison matrices. First we’ll look at the area of intersection. You’ll note that this matrix is symmetrical around the diagonal.</p>
<pre class="r"><code>pander( overlap_stats$overlap_area$iso95 )</code></pre>
<table>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="right">ID0001</th>
<th align="right">ID0002</th>
<th align="right">ID0003</th>
<th align="right">ID0004</th>
<th align="right">ID0005</th>
<th align="right">ID0006</th>
<th align="right">ID0007</th>
<th align="right">ID0008</th>
<th align="right">ID0009</th>
<th align="right">ID0010</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><strong>ID0001</strong></td>
<td align="right">0</td>
<td align="right">20.78</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">126.1</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="center"><strong>ID0002</strong></td>
<td align="right">20.78</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">306.9</td>
<td align="right">71.34</td>
</tr>
<tr class="odd">
<td align="center"><strong>ID0003</strong></td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">112.7</td>
<td align="right">0</td>
<td align="right">229.3</td>
<td align="right">0</td>
<td align="right">124.6</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="center"><strong>ID0004</strong></td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">112.7</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0.2265</td>
<td align="right">15.85</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="center"><strong>ID0005</strong></td>
<td align="right">126.1</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="center"><strong>ID0006</strong></td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">229.3</td>
<td align="right">0.2265</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">141.2</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="center"><strong>ID0007</strong></td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">15.85</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="center"><strong>ID0008</strong></td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">124.6</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">141.2</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="center"><strong>ID0009</strong></td>
<td align="right">0</td>
<td align="right">306.9</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">13.08</td>
</tr>
<tr class="even">
<td align="center"><strong>ID0010</strong></td>
<td align="right">0</td>
<td align="right">71.34</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">13.08</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p>Finally, we’ll look at the matrix which expresses the area of overlap as a proportion of each of the two isopleths. This matrix is <strong>not</strong> symmetrical. For example, the output below tells us that the intersection of the 95% isopleth for <strong>ID0005</strong> and <strong>ID0001</strong> was 12.69% of the area of the 95% isopleth for <strong>ID0005</strong>, and 11.55% of the area for <strong>ID0001</strong>.</p>
<pre class="r"><code>pander(overlap_stats$overlap_prop$iso95)</code></pre>
<table>
<thead>
<tr class="header">
<th align="center"> </th>
<th align="right">ID0001</th>
<th align="right">ID0002</th>
<th align="right">ID0003</th>
<th align="right">ID0004</th>
<th align="right">ID0005</th>
<th align="right">ID0006</th>
<th align="right">ID0007</th>
<th align="right">ID0008</th>
<th align="right">ID0009</th>
<th align="right">ID0010</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><strong>ID0001</strong></td>
<td align="right">0</td>
<td align="right">0.01904</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right"><strong><em>0.1155</em></strong></td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="center"><strong>ID0002</strong></td>
<td align="right">0.02144</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0.3166</td>
<td align="right">0.0736</td>
</tr>
<tr class="odd">
<td align="center"><strong>ID0003</strong></td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0.1775</td>
<td align="right">0</td>
<td align="right">0.3612</td>
<td align="right">0</td>
<td align="right">0.1963</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="center"><strong>ID0004</strong></td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0.09494</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0.0001909</td>
<td align="right">0.01335</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="center"><strong>ID0005</strong></td>
<td align="right"><strong><em>0.1269</em></strong></td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="center"><strong>ID0006</strong></td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0.3959</td>
<td align="right">0.0003912</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0.2439</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="center"><strong>ID0007</strong></td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0.04577</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="center"><strong>ID0008</strong></td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0.1388</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0.1573</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="center"><strong>ID0009</strong></td>
<td align="right">0</td>
<td align="right">0.4001</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0.01705</td>
</tr>
<tr class="even">
<td align="center"><strong>ID0010</strong></td>
<td align="right">0</td>
<td align="right">0.09879</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0.01811</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
</div>
<div id="summary" class="section level3">
<h3>Summary</h3>
<p>The <code>lhs.iso.overlap</code> function from the <tt>tlocoh.dev</tt> package makes it easy to compute the area of intersection of many pairs of hullsets. While not as nuanced as other measures of association, homerange intersection can give you idea of which pairs of individuals share space.</p>
<hr />
<p><strong>T-LoCoH Tips</strong>. If you find this tip useful, or have feedback or another question on how to use T-LoCoH, please contact the <a href="mailto:tlocoh@gmail.com">package author</a>. (c) 2015 <br> <br></p>
</div>


</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
